### ISSUE TITLE
How about the performance of the add-on?

### ISSUE THREAD

**Issue by Yogesh102** [vprince1/alfresco-bulk-export#4]
Hi Vijay,

I have downloaded this add-on and tried on 4.1.4. It worked like a charm without any issues.
It's a really great add-on and I loved it.

Just wondering about the performance benchmark,  because I am going to export a folder which has around 15,000 files beneath it.  

If you can share your own experience or some benchmark then it will be really helpful to me.

Thanks,
Yogesh Prajapati

**Comment by vprince1** [comment]
Hi Yogesh,

I am glad the tool is useful for you. I have used this to export over a million documents without issues. I would usually let it run overnight. The time it takes to export is highly dependent on your servers and most importantly the DB.

Let me know if you run into any issues when processing over 15k files. As best practice, it is better to not have so many files inside a folder.

Vijay

**Comment by Yogesh102** [comment]
Thanks, Vijay for clarification. Actually, I could not use this add-on in my actual production environment since I found another simple way to achieve client's need. Great work Vijay.
